api_image_description = "color: #A0A0A0; font-style: italic;"
api_link = "color: #00C7BD; text-decoration: none;"
console_background = "background-color: #202020;"
runner_info = "color: #A0A0A0; font-style: italic;"
script_arg_value = "color: #E0E0E0; font-weight: bold;"
script_description = "color: white; background-color: #00A29A; padding: 10px;"
script_error_block = "color: white; background-color: #D32F2F; font-weight: bold;"
script_header_block = "color: white; background-color: #388E3C; font-weight: bold;"
script_info = "color: #E0E0E0; font-family: 'Consolas', monospace;"
script_stderr = "color: #FF8A80;"
script_stdout = "color: #E0E0E0;"
script_success_block = "color: white; background-color: #388E3C; font-weight: bold;"
set_header = "color: white; background-color: #00A29A; font-weight: bold; font-size: 11pt;"
set_info = "color: #E0E0E0;"
status_error = "background-color: #D32F2F; color: white;"
status_pending = "background-color: transparent; color: #A0A0A0;"
status_running = "background-color: #00A29A; color: white;"
status_skipped = "background-color: #383838; color: #A0A0A0;"
status_success = "background-color: transparent; color: #81C784;"
tooltip_arg_value = "color: #00C7BD;"
tooltip_instance_args_block = "background-color: rgba(0, 162, 154, 0.1); border-left: 3px solid #00A29A; padding: 5px;"
tooltip_script_args_block = "background-color: rgba(74, 74, 74, 0.2); border-left: 3px solid #4A4A4A; padding: 5px;"
delegate_hover_border = "color: #00A29A;"
delegate_changed_indicator = "color: #D32F2F;"
delegate_preview_background = "color: #383838;"
delegate_secondary_text = "color: #A0A0A0;"