# Пороги для анализа состояния глаз (Eye Aspect Ratio)
# Определяют границы для состояний: [закрыты, прищурены, открыты]
eye_2d_ratio_thresholds = [0.22, 0.264, 0.3]

# Пороги для анализа состояния рта (Mouth Aspect Ratio)
# Определяют границы для состояний: [закрыт, приоткрыт, открыт]
mouth_2d_ratio_thresholds = [0.04, 0.1, 0.22]

# Пороги для анализа позы головы (в градусах)
[head_pose_thresholds]
# Границы для оценки поворота по горизонтали (yaw)
# [сильно влево, влево, немного влево, прямо, немного вправо, вправо, сильно вправо]
yaw_thresholds = [-30.0, -15.0, -5.0, 5.0, 15.0, 30.0]

# Границы для оценки наклона по вертикали (pitch)
# [сильно вниз, ..., сильно вверх]
pitch_thresholds = [-25.0, -10.0, -5.0, 5.0, 10.0, 25.0]

# Границы для оценки бокового наклона (roll)
# [сильный наклон влево, ..., сильный наклон вправо]
roll_thresholds = [-25.0, -10.0, -5.0, 5.0, 10.0, 25.0]