# gui_lib/ui_texts.py

"""
Модуль для хранения всех текстовых констант и локализованных строк
для пользовательского интерфейса.
"""

UI_TEXTS = {
    "window_title": "Предварительный анализ фотографий",
    "config_label": "Текущая конфигурация:",
    "config_browse_btn": "Обзор...",
    "config_load_btn": "Обновить",
    "paths_group_title": "Настроить путь к рабочим папкам",
    "folder_path_label": "Папка с исходными фотографиями:",
    "folder_path_browse_btn": "Выбрать...",
    "folder_path_dialog_title": "Выбор папки с фотографиями",
    "output_path_label": "Папка для хранения результатов:",
    "output_path_browse_btn": "Выбрать...",
    "output_path_dialog_title": "Выбор папки для результатов",
    "model_root_label": "Папка для размещение моделей:",
    "model_root_browse_btn": "Выбрать...",
    "model_root_dialog_title": "Выбор папки моделей",
    "provider_cache_label": "Папка кэша TensorRT:",
    "provider_cache_browse_btn": "Выбрать...",
    "provider_cache_dialog_title": "Выбор папки кэша TensorRT",
    "tasks_group_title": "Доступные задачи",
    "task_run_image_analysis_and_clustering": "Выполнить анализ и кластеризацию",
    "task_analyze_gender": "Определить пол",
    "task_analyze_emotion": "Определить базовую эмоцию",
    "task_analyze_age": "Определить возраст",
    "task_analyze_beauty": "Определить привлекательность",
    "task_analyze_eyeblink": "Определить состояние глаз",
    "task_keypoint_analysis": "Анализировать ключевые точки",
    "task_create_xmp_file": "Создать XMP-файл",
    "task_move_files_to_claster": "Сортировать по папкам",
    "task_generate_html": "Создать HTML-отчет ",
    "moving_group_title": "Параметры сортировки",
    "moving_move_copy_check": "Перемещать файлы при сортировке (иначе копировать)",
    "moving_extensions_label": "Расширение сортируемых файлов:",
    "moving_ext_placeholder": ".jpg",
    "moving_add_btn": "+",
    "moving_del_btn": "-",
    "report_group_title": "Параметры генерации HTML-отчета",
    "report_thumb_label": "Размер миниатюр изображений (px):",
    "report_vis_method_label": "Метод визуализации кластеров:",
    "provider_label": "Провайдер:",
    "provider_combo_auto": "Авто",
    "processing_group_title": "Параметры базового анализа изображений",
    "proc_image_type_label": "Тип обрабатываемых файлов:",
    "proc_save_jpeg_check": "Сохранять JPEG извлеченный из RAW/PSD файла",
    "proc_min_prev_label": "Мин.размер JPEG (px):",
    "proc_target_size_label": "Target Size (W, H):",
    "proc_max_workers_label": "Max Workers (0=авто):",
    "proc_max_workers_tooltip": "0 = авто (CPU cores)",
    "proc_block_size_label": "Block Size (0=все):",
    "proc_max_limit_label": "Max Workers Limit:",
    "proc_xmp_tasks_label": "Max XMP Tasks:",
    "proc_raw_ext_label": "RAW расширения:",
    "proc_raw_ext_placeholder": ".nef",
    "proc_add_btn": "+",
    "proc_del_btn": "-",
    "clustering_group_title": "Параметры кластеризации фотографий",
    "clus_portrait_group": "Портретные фотографии",
    "clus_group_group": "Групповые фотографии",
    "clus_algo_label": "Алгоритм кластеризации:",
    "clus_eps_label": "Eps / Clus Eps:",
    "clus_min_samples_label": "Минимальный размер кластера:",
    "clus_group_eps_label": "Eps:",
    "clus_group_min_samples_label": "Минимальный размер кластера:",
    "log_level_label": "Уровень логирования:",
    "debug_group_title": "Параметры отладки",
    "debug_save_kps_check": "Сохранять отладочные изображения с KPS",
    "save_config_btn": "Сохранить файл конфигурации",
    "run_btn": "Запустить обработку",
    "exit_btn": "Выход",
    "log_area_label": "Лог выполнения:",
    "progress_label": "Прогресс:",
    "dialog_select_config_title": "Выбрать файл конфигурации",
    "dialog_select_config_filter": "TOML Files (*.toml);;All Files (*.*)",
    "dialog_save_config_title": "Сохранить конфигурацию как...",
    "dialog_save_config_filter": "TOML Files (*.toml);;All Files (*.*)",
    "dialog_select_folder_title": "Выбрать папку",
    "msg_error": "Ошибка",
    "msg_warning": "Внимание",
    "msg_info": "Информация",
    "msg_file_not_found": "Файл не найден:\n{}",
    "msg_load_error": "Ошибка загрузки:\n{}\n\n{}",
    "msg_save_error": "Не удалось сохранить конфигурацию:\n{}\n\n{}",
    "msg_load_validate_error": "Не удалось загрузить или провалидировать:\n{}",
    "msg_config_path_missing": "Путь к файлу конфигурации не указан.",
    "msg_processing_running": "Обработка уже запущена.",
    "msg_confirm_run_title": "Подтверждение запуска",
    "msg_confirm_run_text": 'Текущие настройки GUI будут сохранены в файл:\n"{}"\n\nЗапустить обработку?',
    "msg_save_cancelled": "Сохранение отменено пользователем. Запуск прерван.",
    "msg_config_not_found_run": "Файл конфигурации для запуска не найден или не указан:\n{}",
    "msg_processing_finished": "Обработка завершена!",
    "msg_processing_status": "Статус: {}",
    "msg_status_success": "Успешно",
    "msg_status_error": "С ошибками",
    "msg_critical_error": "Произошла критическая ошибка:\n{}\n\nСмотрите детали в логе.",
    "msg_config_saved": "Конфигурация сохранена.",
    "msg_ext_already_exists": "Элемент '{}' уже есть в списке.",
    "msg_ext_invalid_prefix": "Введите корректное значение (должно начинаться с '{}').",
    "msg_ext_select_to_remove": "Выберите элемент для удаления.",
    "msg_config_read_fail_warning": "Предупреждение: Не удалось прочитать начальный конфиг для уровня лога: {}",
    "msg_python_version_error": "Ошибка версии Python",
    "msg_python_version_required": "Требуется Python 3.8 или новее.",
    "msg_gui_error_critical": "Критическая ошибка GUI",
    "msg_gui_unhandled_error": "Произошла неперехваченная ошибка:\n{}\n\nСмотрите лог-файл.",
    "msg_gui_cannot_show_error": "Не удалось показать GUI сообщение об ошибке: {}",
    "msg_log_level_invalid": "Некорректный уровень логирования '{}' в конфиге. Установлен INFO.",
    "msg_provider_added_warning": "Провайдер '{}' из конфига добавлен в список GUI.",
    "msg_config_validation_warning": "Конфиг не прошел валидацию: {}. Сохраняем как есть.",
    "msg_gui_update_error": "Не удалось полностью обновить интерфейс из файла:\n{}\n\n{}",
}