# ==============================================================================
# Конфигурационный файл для этапа кластеризации локаций
# ==============================================================================

[paths]
# Корневая папка, где лежат подпапки с моделями
model_root = "../../../../_BIN"
# Путь к ONNX-модели CLIP Vision Encoder относительно model_root
clip_model_onnx = "models/CLIP/ViT-L-14.onnx"


[provider]
# Имя провайдера. Оставьте пустым для автовыбора.
# Варианты: "TensorrtExecutionProvider", "CUDAExecutionProvider", "CPUExecutionProvider"
provider_name = ""
device_id = 0
tensorRT_cache_path = "../../../../_BIN/TensorRT_cache"
# Уровень оптимизации сборщика. 3 - стандартный уровень.
trt_builder_optimization_level = 3
# Максимальный размер рабочего пространства (в байтах). 4 ГБ - хорошее значение.
trt_max_workspace_size = "4294967296"


[model_params]
# Размер входного изображения для модели CLIP
input_size = [224, 224]


[clustering]
# Параметры для алгоритма DBSCAN (режим кластеризации)
# min_samples: Минимальное количество изображений для формирования кластера (локации).
min_samples = 2
# Метрика расстояния. Для эмбеддингов CLIP 'cosine' является наилучшим выбором.
metric = "cosine"


[classification]
# Порог косинусного сходства для режима классификации.
# Если сходство изображения с лучшим промптом ниже этого порога,
# оно будет помечено как "шум" (метка -1).
# Значение от 0.0 до 1.0.
match_threshold = 0.25