# Configuration for RMBG/BiRefNet Tool
# Версия конфига: 1.0.0

# --- Основной выбор процессора ---
# Выберите модуль, который будет использоваться для обработки.
# Доступные значения:
# "rmbg"     - Фасад для моделей RMBG-2.0, INSPYRENET, BEN, BEN2.
# "birefnet" - Фасад для специализированных моделей BiRefNet (general, HR, portrait и т.д.).
processor_type = "rmbg"

# --- Общие настройки моделей и постобработки ---
# Эти настройки используются как значения по умолчанию.
[model]
# Имя конкретной модели, которую нужно использовать.
# Убедитесь, что модель совместима с выбранным `processor_type`.
# Для 'rmbg': "RMBG-2.0", "INSPYRENET", "BEN", "BEN2"
# Для 'birefnet': "BiRefNet-general", "BiRefNet-HR", "BiRefNet-portrait" и др.
name = "RMBG-2.0"

# --- Пути ---
# Укажите пути к вашим папкам. Относительные пути (../) работают.
[paths]
input_dir = "./_input"
output_dir = "./_output"
# Важно! Укажите папку, где будут храниться все скачанные модели.
model_root = "D:/WORK_PYTHON2025/PySM/_BIN/models"

# --- Общие параметры постобработки ---
# Эти значения могут быть переопределены в специфичных секциях ниже
# или через интерфейс PyScriptManager.
mask_blur = 0        # Размытие краев маски по Гауссу (0 = выключено).
mask_offset = 0      # Смещение краев маски в пикселях (+ расширяет, - сужает).
background = "Alpha" # Тип фона: "Alpha" (прозрачный), "Solid" (сплошной цвет), "Original" (исходный).
background_color = [255, 255, 255] # Цвет для фона "Solid" в формате [R, G, B].
invert_output = false # Инвертировать ли финальную маску (черное станет белым).

# --- Опции сохранения ---
save_image = true # Сохранять итоговое изображение с обработанным фоном.
save_mask = true  # Сохранять черно-белую маску как отдельный файл.


# --- Специфичные настройки для процессора 'rmbg' ---
[rmbg_specific]
# Этот параметр используется только моделью BEN2.
refine_foreground = true # Улучшает детализацию, но замедляет обработку.


# --- Специфичные настройки для процессора 'birefnet' ---
[birefnet_specific]
# Вы можете принудительно задать разрешение для обработки изображений.
# Если не указано, будет использовано разрешение по умолчанию для каждой модели.
# img_scale = 1024


# --- Настройки логирования ---
[logging]
logging_level = "INFO" # Уровни: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
log_file = "rmbg_process.log"