[paths]
python_interpreter = "../../envs/pysm/python.exe"
additional_env_paths = []
python_paths = []

[ui]
last_used_script_set = "setnode_248fdda481cb"
last_used_sets_collection_file = "script_collections/Рабочий процесс. Сезон 2026.pysmc"

[logging]
log_level = "INFO"

[general]
language = "ru_RU"
active_theme_name = "default"

[environment_variables]
NO_ALBUMENTATIONS_UPDATE = "1"
