[paths]
python_interpreter = "../../envs/pysm/Scripts/python.exe"
additional_env_paths = []
python_paths = []

[ui]
last_used_script_set = ""

[logging]
log_level = "INFO"

[general]
language = "ru_RU"
active_theme_name = "default"

[environment_variables]
NO_ALBUMENTATIONS_UPDATE = "1"
