api_image_description = "color: #8b949e; font-size: 10pt; font-style: italic;"
api_link = "color: #58a6ff; font-size: 11pt; text-decoration: underline; font-weight: normal;"
collection_info = "background-color: #2d333b; padding: 5px; border-radius: 5px;"
console_background = "background-color: #22272e;"
runner_info = "color: #8b949e; font-style: italic;"
script_arg_value = "color: #79c0ff;"
script_description = "color: #cdd5df; background-color: #316dca; font-size: 10pt; padding: 10px;"
script_error_block = "color: #ffffff; background-color: #d15766; font-weight: bold;"
script_header_block = "color: #ffffff; background-color: #2ea043; font-weight: bold;"
script_info = "color: #8b949e; font-family: 'Consolas', 'Courier New', monospace;"
script_stderr = "color: #ff938a;"
script_stdout = "color: #adbac7;"
script_success_block = "color: #ffffff; background-color: #2ea043; font-weight: bold;"
set_header = "color: #ffffff; background-color: #316dca; font-weight: bold;"
set_info = "color: #adbac7;"
status_error = "background-color: #d15766; color: #ffffff;"
status_pending = "background-color: transparent; color: #8b949e;"
status_running = "background-color: #2ea043; color: #ffffff;"
status_skipped = "background-color: #444c56; color: #8b949e;"
status_success = "background-color: transparent; color: #58a6ff;"
tooltip_arg_value = "color: #58a6ff;"
tooltip_instance_args_block = "background-color: #2d333b; padding: 5px; border-radius: 5px; border: 1px solid #444c56;"
tooltip_script_args_block = "background-color: #2d333b; padding: 5px; border-radius: 5px; border: 1px solid #444c56;"
delegate_hover_border = "color: #58a6ff;"
delegate_changed_indicator = "color: #d15766;"
delegate_preview_background = "color: #2d333b;"
delegate_secondary_text = "color: #8b949e;"