# themes/silver_fluent/theme.toml

api_image_description = "color: #555555; font-style: italic;"
api_link = "color: #0066cc; text-decoration: none;"
console_background = "background-color: #ffffff;"
runner_info = "color: #777777; font-style: italic;"
script_arg_value = "color: #000000; font-weight: bold;"
script_description = "color: #1c1c1c; background-color: #e5f1fb; padding: 10px;"
script_error_block = "color: white; background-color: #c82333; font-weight: bold;"
script_header_block = "color: white; background-color: #218838; font-weight: bold;"
script_info = "color: #333333; font-family: 'Consolas', monospace;"
script_stderr = "color: #c82333;"
script_stdout = "color: #1c1c1c;"
script_success_block = "color: white; background-color: #218838; font-weight: bold;"
set_header = "color: white; background-color: #0078d7; font-weight: bold; font-size: 11pt;"
set_info = "color: #1c1c1c;"
status_error = "background-color: #f8d7da; color: #721c24;"
status_pending = "background-color: transparent; color: #555555;"
status_running = "background-color: #cce4f7; color: #004085;"
status_skipped = "background-color: #e2e3e5; color: #383d41;"
status_success = "background-color: transparent; color: #155724;"
tooltip_arg_value = "color: #0078d7;"
tooltip_instance_args_block = "background-color: #f8f9fa; border-left: 3px solid #0078d7; padding: 5px;"
tooltip_script_args_block = "background-color: #f8f9fa; border-left: 3px solid #cccccc; padding: 5px;"
delegate_hover_border = "color: #0078d7;"
delegate_changed_indicator = "color: #c82333;"
delegate_preview_background = "color: #e8e8e8;"
delegate_secondary_text = "color: #555555;"
