api_image_description = "color: #8c8c8c; font-size: 10pt; font-style: italic;"
api_link = "color: #3794ff; font-size: 11pt; text-decoration: underline; font-weight: normal;"
collection_info = "background-color: #252526; padding: 5px; border-radius: 5px;"
console_background = "background-color: #1e1e1e;"
runner_info = "color: #808080; font-style: italic;"
script_arg_value = "color: #9cdcfe;"
script_description = "color: #d4d4d4; background-color: #0e639c; font-size: 10pt; padding: 10px;"
script_error_block = "color: #f14c4c; font-weight: bold;"
script_header_block = "color: #4ec9b0; font-weight: bold;"
script_info = "color: #8c8c8c; font-family: 'Consolas', 'Courier New', monospace;"
script_stderr = "color: #f14c4c;"
script_stdout = "color: #d4d4d4;"
script_success_block = "color: #4ec9b0; font-weight: bold;"
set_header = "color: #ffffff; background-color: #094771; font-weight: bold;"
set_info = "color: #cccccc;"
status_error = "background-color: #5f1e1e; color: #f14c4c;"
status_pending = "background-color: transparent; color: #808080;"
status_running = "background-color: #264f78; color: #d4d4d4;"
status_skipped = "background-color: #3e3e42; color: #808080;"
status_success = "background-color: transparent; color: #4ec9b0;"
tooltip_arg_value = "color: #3794ff;"
tooltip_instance_args_block = "background-color: #252526; padding: 5px; border-radius: 5px; border: 1px solid #3e3e42;"
tooltip_script_args_block = "background-color: #252526; padding: 5px; border-radius: 5px; border: 1px solid #3e3e42;"
delegate_hover_border = "color: #0078d7;"
delegate_changed_indicator = "color: #f14c4c;"
delegate_preview_background = "color: #2d2d30;"
delegate_secondary_text = "color: #8c8c8c;"