# ==============================================================================
# Конфигурационный файл для этапа анализа лиц (run_analyze_faces.py)
# ==============================================================================

[paths]
model_root = "../../../../_BIN"

[provider]
provider_name = ""
device_id = 0
tensorRT_cache_path = "../../../../_BIN/TensorRT_cache"

[model]
gender_model = "models/FACEONNX/gender_efficientnet_b2.onnx"
emotion_model = "models/FACEONNX/emotion_cnn.onnx"
age_model = "models/FACEONNX/age_efficientnet_b2.onnx"
beauty_model = "models/FACEONNX/beauty_resnet18.onnx"
eyeblink_model = "models/FACEONNX/eye_blink_cnn.onnx"

emotion_labels =["Neutral", "Happiness", "Surprise", "Sadness", "Anger", "Disgust", "Fear"]

[eye_thresholds]
# Новые границы размеров лиц в пикселях (под высокое разрешение)
size_limits = [180, 300]
# --- Категория размера: SMALL ---
# Всего проанализировано глаз: 8007
# Статистика: Min=0.002, Q1=0.014, Median=0.023, Q3=0.075, Max=1.000
thresholds_small =[0.014, 0.023]

# --- Категория размера: MEDIUM ---
# Всего проанализировано глаз: 3528
# Статистика: Min=0.000, Q1=0.868, Median=0.984, Q3=0.998, Max=1.000
thresholds_medium =[0.2, 0.4]

# --- Категория размера: LARGE ---
# Всего проанализировано глаз: 4
# Статистика: Min=0.983, Q1=0.996, Median=1.000, Q3=1.000, Max=1.000
thresholds_large =[0.3, 0.600]
