api_image_description = "color: #33FF33; font-style: italic;"
api_link = "color: #44EE44; text-decoration: underline;"
collection_info = "background-color: #1A4A1A; padding: 5px;"
console_background = "background-color: #0A0F0A;"
runner_info = "color: #22AA22; font-style: italic;"
script_arg_value = "color: #77FF77;"
script_description = "color: #0A0F0A; background-color: #22AA22; padding: 10px;"
script_error_block = "color: #FFFF55; background-color: #880000; font-weight: bold;"
script_header_block = "color: #0A0F0A; background-color: #33FF33; font-weight: bold;"
script_info = "color: #33FF33;"
script_stderr = "color: #FFB833;" # Янтарный/Оранжевый для ошибок
script_stdout = "color: #33FF33;" # Зеленый для обычного вывода
script_success_block = "color: #0A0F0A; background-color: #33FF33; font-weight: bold;"
set_header = "color: #0A0F0A; background-color: #33FF33; font-weight: bold;"
set_info = "color: #77FF77;"
status_error = "background-color: #FFB833; color: #0A0F0A;"
status_pending = "background-color: transparent; color: #22AA22;"
status_running = "background-color: #33FF33; color: #0A0F0A;"
status_skipped = "background-color: #1A4A1A; color: #22AA22;"
status_success = "background-color: transparent; color: #77FF77;"
tooltip_arg_value = "color: #77FF77;"
tooltip_instance_args_block = "background-color: #1A4A1A; border: 1px solid #22AA22; padding: 5px;"
tooltip_script_args_block = "background-color: #1A4A1A; border: 1px solid #22AA22; padding: 5px;"