logging_level = "INFO"

[debug]
save_analyzed_kps_images = false

[paths]
folder_path = "G:\\2025\\222"
output_path = "G:\\2025\\222\\34"
model_root = "..\\..\\..\\_BIN"
tensorRT_cache_path = "..\\..\\..\\_BIN\\TensorRT_cache"
children_file = ""

[task]
run_image_analysis_and_clustering = true
analyze_gender = true
analyze_emotion = true
analyze_age = true
analyze_beauty = false
analyze_eyeblink = true
keypoint_analysis = true
create_xmp_file = false
move_files_to_claster = false
generate_html = true

[moving]
move_or_copy_files = true
file_extensions_to_action = [ ".jpeg", ".jpg", ".xmp",]

[provider]
provider_name = "TensorrtExecutionProvider"

[model]
name = "antelopev2"
det_thresh = 0.25
det_size = [ 1280, 1280,]
gender_model_filename = "models/FACEONNX/gender_efficientnet_b2.onnx"
emotion_model_filename = "models/FACEONNX/emotion_cnn.onnx"
age_model_filename = "models/FACEONNX/age_efficientnet_b2.onnx"
beauty_model_filename = "models/FACEONNX/beauty_resnet18.onnx"
eyeblink_model_filename = "models/FACEONNX/eye_blink_cnn.onnx"
emotion_labels = [ "Neutral", "Happiness", "Surprise", "Sadness", "Anger", "Disgust", "Fear",]
eyeblink_labels = [ "Closed", "Open",]
eyeblink_threshold = 0.5

[processing]
select_image_type = "RAW"
raw_extensions = [ ".nef", ".cr2", ".arw", ".cr3",]
psd_extensions = [ ".psd", ".psb",]
save_jpeg = true
min_preview_size = 1024
target_size = [ 640, 640,]
max_workers = 8
block_size = 0
max_workers_limit = 16
max_concurrent_xmp_tasks = 50

[matching]
match_threshold = 0.25
use_auto_threshold = false
percentile = 25

[report]
thumbnail_size = 200
visualization_method = "PCA"
analyze_keypoints = true

[visualization]
base_point_radius = 1
base_font_size = 20
point_color = [ 0, 255, 0,]
font_color = [ 255, 0, 0,]
background_color = [ 255, 255, 255,]
background_alpha = 0.7

[xmp]
exclude_fields = [ "cluster_label", "child_name", "matched_portrait_cluster_label", "matched_child_name", "match_distance", "landmark_3d_68", "gender_insight", "age_insight",]

[report.keypoint_analysis]
eye_2d_ratio_thresholds = [ 0.22, 0.264, 0.3,]
eye_z_diff_threshold = 0.05
mouth_2d_ratio_thresholds = [ 0.04, 0.1, 0.22,]
mouth_z_diff_thresholds = [ 0.02, 0.04, 0.06,]
emotion_model_path = "models/emotion_ferplus-7.onnx"

[report.tsne]
perplexity = 30
max_iter = 1000
random_state = 42

[report.pca]
n_components = 2
random_state = 42

[clustering.portrait]
algorithm = "DBSCAN"
eps = 0.25
min_samples = 1
metric = "cosine"

[clustering.group]
algorithm = "DBSCAN"
eps = 0.3
min_samples = 2
metric = "cosine"
use_auto_eps = false
percentile = 95
visualize = true
