# ===============================================
# Глобальные настройки для приложения mask_sam2
# ===============================================
[global]
# Путь для кэширования всех моделей (относительно корня проекта img2mask)
model_dir = "../../../_BIN/models/RMBG"
# Устройство для вычислений: "auto", "cpu", "cuda"
device = "auto"
# Количество параллельных потоков для обработки
num_threads = 4

# ===============================================
# Настройки для сегментации по тексту
# ===============================================
[segment]
# Модели по умолчанию для сегментации
sam_model_name = "SAM2-Hiera-L"
dino_model_name = "GroundingDINO-B"
threshold = 0.40

# --- Параметры постобработки маски ---
[segment.postprocess]
background = "Alpha"  # "Alpha" или "Color"
background_color = "#000000"
mask_blur = 2
mask_offset = 0
smooth = 1.0
fill_holes = true
invert_output = false