api_image_description = "color: #6c757d; font-size: 11pt; font-style: italic; background-color: transparent; padding: 2px;"
api_link = "color: #0077b6; font-size: 12pt; text-decoration: underline; font-weight: normal;"
collection_info = "background-color: #e8f0fe; padding: 5px; border-radius: 3px;"
console_background = "background-color: #ffffff;"
runner_info = "color: #808080; font-style: italic;"
script_arg_value = "color: #005a9e;"
script_description = "color: #ffffff; background-color: #0077b6; font-size: 10pt; padding: 10px;"
script_error_block = "color: #ffffff; background-color: #c0392b; font-weight: bold;"
script_header_block = "color: #ffffff; background-color: #27ae60; font-weight: bold;"
script_info = "color: #555555; font-family: 'Courier New', monospace;"
script_stderr = "color: #e74c3c;"
script_stdout = "color: #000000;"
script_success_block = "color: #ffffff; background-color: #27ae60; font-weight: bold;"
set_header = "color: #ffffff; background-color: #0078d7; font-weight: bold;"
set_info = "color: #005a9e;"
status_error = "background-color: #f8d7da; color: #721c24;"
status_pending = "background-color: transparent; color: #383d41;"
status_running = "background-color: #d4edda; color: #155724;"
status_skipped = "background-color: #e2e3e5; color: #383d41;"
status_success = "background-color: transparent; color: #155724;"
tooltip_arg_value = "color: #0078d7;"
tooltip_instance_args_block = "background-color: #e8f5e9; padding: 5px; border-radius: 5px; border: 1px solid #d0e8d2;"
tooltip_script_args_block = "background-color: #e5f1fb; padding: 5px; border-radius: 5px; border: 1px solid #d0e0f0;"
delegate_hover_border = "color: #0078d7;"
delegate_changed_indicator = "color: #f0ad4e;"
delegate_preview_background = "color: #e8e8e8;"
delegate_secondary_text = "color: #555555;"
